### ISSUE TITLE
Cannot set `innerHTML`

### ISSUE THREAD

**Issue by CasperWA** [materialscloud-org/voila-materialscloud-template#13]
I am seeing some issues when running Voilà using this template stating; `TypeError: Cannot set property 'innerHTML' of null
`. I believe this is due to this template.

The following is an excerpt from `index.js`, where the issue is found in the script below, specifically when setting `innerHTML`.

```html
  <script type="text/javascript">
    requirejs(['static/voila'], function(voila) {
      (async function() {
        var kernel = await voila.connectKernel();

        kernel.statusChanged.connect(() => {
          // console.log(kernel.status);
          var el = document.getElementById("kernel-status-icon");

          if (kernel.status == 'busy') {
            el.innerHTML = 'radio_button_checked';
          } else {
            el.innerHTML = 'radio_button_unchecked';
          }
        });
      })();
    });
  </script>
```

**Comment by CasperWA** [comment]
Testing this without using this template, the error does indeed _not_ show up.

**Comment by dou-du** [comment]
You are right. This should be removed. This is not needed in the materialscloud template. It is used in the OSSCAR and Aiidalab template.

**Comment by CasperWA** [comment]
> You are right. This should be removed. This is not needed in the materialscloud template. It is used in the OSSCAR and Aiidalab template.

Why is it used there? Do you have a checkbox that changes if the kernel is active or not?
