### ISSUE TITLE
No header template

### ISSUE THREAD

**Issue by CasperWA** [materialscloud-org/voila-materialscloud-template#15]
In conversations between @ltalirz, @asle85 and myself it seems the easiest way of implementing Voilà applications into the dokku server to be used as MaterialsCloud tools is to remove the header in this template and put in the application using an `iframe`.

However, this is still under discussion, but this issue is here to follow the decisions taken within the MaterialsCloud team.

**Comment by CasperWA** [comment]
I have created the [`lite`](https://github.com/materialscloud-org/voila-materialscloud-template/tree/lite) branch.
This has been updated with the necessary iframe options as well.

I will create a separate repository for this template.

**Comment by ltalirz** [comment]
I don't mind either way - it can make sense to keep both in the same place.
If it turns out in a couple of months that the fully blown materials cloud template is no longer used we can always decide to remove later to make the package lighter.

**Comment by dou-du** [comment]
> I have created the [`lite`](https://github.com/materialscloud-org/voila-materialscloud-template/tree/lite) branch.
> This has been updated with the necessary iframe options as well.
> 
> ~I will create a separate repository for this template.~
> I think instead I will simply add it to this repository as a second template that will be installed alongside `materialscloud`. I'll name it `materialscloud-iframe`.
> What do you think @dou-du, @ltalirz, @giovannipizzi?

There may be another solution. We can consider to use the "theme" parameter. So we can have one single template, which can be toggled with different theme.

**Comment by CasperWA** [comment]
> There may be another solution. We can consider to use the "theme" parameter. So we can have one single template, which can be toggled with different theme.

Not a bad idea, but it seems conceptually to fall a bit out of place for this. Keeping it a template seems better to me, but I'm not as such opposed to the idea :)
