### ISSUE TITLE
The spinner may not appear with Binder 

### ISSUE THREAD

**Issue by dou-du** [materialscloud-org/voila-materialscloud-template#20]
Hi @CasperWA , I try implement similar spinner for OSSCAR template. I found that it can not load the spinner image.

https://github.com/materialscloud-org/voila-materialscloud-template/blob/78986cbb168b0ee8c0119cb64cfe3a0cc1825162/share/jupyter/voila/templates/materialscloud/spinner.macro.html.j2#L17

I try to replace it with src="{{ base_url }}voila/static/images/mcloud_spinner.svg". However, it is still not working. I am trying
to figure out why this is not working.

**Comment by dou-du** [comment]
I think the best solution is putting the svg directly in the .j2 file. I will try it.

**Comment by CasperWA** [comment]
> Hi @CasperWA , I try implement similar spinner for OSSCAR template. I found that it can not load the spinner image.

Can you link me your implementation for this?

> I try to replace it with src="{{ base_url }}voila/static/images/mcloud_spinner.svg". However, it is still not working. I am trying
> to figure out why this is not working.

This doesn't seem to work, because it takes the `base_url` here to be the current full URL, i.e., the full URL including `/voila/render/example.ipynb` or whereever your notebook is located. Hence, I found changing it to the "absolute" URL path (prepending the `src` value with a slash (`/`)) worked for the MaterialsCloud template.
You need to still place the `svg` file in the `static/images` folder, however.

**Comment by CasperWA** [comment]
The `base_url` issue may be related to the fixed voila-dashboards/voila#734 issue as well? If yes, then updating to Voilà v0.2.4 should fix this issue.

**Comment by dou-du** [comment]
> The `base_url` issue may be related to the fixed [voila-dashboards/voila#734](https://github.com/voila-dashboards/voila/issues/734) issue as well? If yes, then updating to Voilà v0.2.4 should fix this issue.

Voila 0.2.4 seems not help. If you check the Binder link on branch "dou":

https://github.com/materialscloud-org/voila-materialscloud-template/issues/20#issuecomment-716466829

When you refresh the page, we cannot see the spinner. Also the same for the "develop" branch.

**Comment by CasperWA** [comment]
Ah, it seems it adds `/hub` to the beginning of the URL path.

**Comment by CasperWA** [comment]
> I think the best solution is putting the svg directly in the .j2 file. I will try it.

I tried doing this also in my other PR.
Getting the animation right is then a pain in the neck. So trying to stay with the current format is by far the easiest.
I am currently testing a solution in the [`fix_20_spinner-broken-in-binder`](https://github.com/materialscloud-org/voila-materialscloud-template/tree/fix_20_spinner-broken-in-binder) branch (see on [binder](https://mybinder.org/v2/gh/materialscloud-org/voila-materialscloud-template/fix_20_spinner-broken-in-binder?urlpath=%2Fvoila%2Frender%2Fexample-notebooks%2Fexample.ipynb)).

Currently, it's working locally with `../` prepended in the `src`, however, on binder it only works if the `src` is prepended with `../../`, I don't really know why.
