### ISSUE TITLE
"Spinner" not showing up properly when iframed

### ISSUE THREAD

**Issue by CasperWA** [materialscloud-org/voila-materialscloud-template#25]
Using Google Chrome on Win 10.
The Materials Cloud "spinner" shows up cut off (clipped) when iframed on the Materials Cloud website (see e.g., https://materialscloud.org/work/tools/optimadeclient).

**Comment by CasperWA** [comment]
The same is true on Ubuntu 20.04.1 LTS with Firefox.

Here it's even also clipped in the bottom.

![Screenshot from 2020-11-10 16-41-41](https://user-images.githubusercontent.com/43357585/98696206-cba91880-2373-11eb-86ad-f7c6f5a099e3.png)

**Comment by CasperWA** [comment]
From @giovannipizzi:

> It's probably because we're dynamically deciding the iframe size with the iframeresizer tool, to avoid having a 'scroll in scroll' effect.
> This requires a specific <div> at the bottom of the page.

I have already added this to the "final" HTML page that presents the calculated cells, but it might be missing in the loading page HTML and should be added here.

**Comment by giovannipizzi** [comment]
After some non-obvious checking, since the Running page goes away quickly, I think the problem is that the footer (the "hosted on..." + the iframe-resizer marker div) are *after* `</body>`:
```html
[...]
</body>

  <div>
    <p style="text-align: center;">
      Hosted on <a href="https://materialscloud.org" target="_blank"><img src="/voila/templates/materialscloud-iframe/static/images/MaterialsCloud_Horizontal_White.png?v=9d72a25e19ab65e72c2e2ece2c57e9309e0f009c906655415b19c38cf92d35740f353b962ed6d1f3de1018042326b766d7c073e6cb3629a3bb9ae513f2306432" alt="Materials Cloud" width="95" height="25"></a>
    </p>
  </div>
  <div style="position: relative" data-iframe-height></div>
[...]
```

Probably the browser is smart/error-resilient enough to still show the footer, but the JS will not find the div when inspecting the DOM and looking or the special div inside the body?

**Comment by giovannipizzi** [comment]
(Note that in normal pages, instead, the <div> is inside the <body>)

**Comment by CasperWA** [comment]
> After some non-obvious checking, since the Running page goes away quickly, I think the problem is that the footer (the "hosted on..." + the iframe-resizer marker div) are _after_ `</body>`:
> (...)
> Probably the browser is smart/error-resilient enough to still show the footer, but the JS will not find the div when inspecting the DOM and looking or the special div inside the body?

Hmm, probably - but the end page seems to have the proper heigh. So again, I'm drawn more to the fact that the initial loading page _does not have_ this `<div>` element for resizing.
I don't think that it should matter for the JS whether the div is inside `<body>` or not, since I'm sure it simply searches for it wherever it is. The proof being the end result seen when the template is used.

So again, i think the solution is to make sure this `<div>` is included in the "loading" HTML page.
