### ISSUE TITLE
Change "spinner" page text

### ISSUE THREAD

**Issue by CasperWA** [materialscloud-org/voila-materialscloud-template#26]
As mentioned by @giovannipizzi at the internal MaterialsCloud meeting on 10.11.2020, the text on the spinner page should be changed away from mentioning "redirect".

Personally, I think it should simply state "Loading..." or similar.

**Comment by amitkumardeol** [comment]
@CasperWA Can we use "Now Loading... If it doesn't finish loading, click here."

**Comment by CasperWA** [comment]
> @CasperWA Can we use "Now Loading... If it doesn't finish loading, click here."

Sure.
My intent was to substitute the part of the string mentioning "redirect" to mention "loading" instead, so the complete string would indeed end up looking like the string you suggest.

**Comment by CasperWA** [comment]
Closed by #27
