### ISSUE TITLE
No text when iframed and loading

### ISSUE THREAD

**Issue by CasperWA** [materialscloud-org/voila-materialscloud-template#29]
At the moment, you can see at https://dev-www.materialscloud.org/work/tools/optimadeclient that while the logo is now visible, the text "Loading..." etc. does not show up.

**Comment by unkcpz** [comment]
Ah, sorry, this is the template repository. Not sure this is fix or not but we don't have the issue in optimadeclient with iframe template before. Feel free to re-open if I'm wrong.
