### ISSUE TITLE
Bullet points not shown

### ISSUE THREAD

**Issue by CasperWA** [materialscloud-org/voila-materialscloud-template#5]
Bullet points are not shown properly (and with differently sized text as well).
In the image below the listings under the FAQ should have bullet points, the size difference is also evident:

![matcloud_template2](https://user-images.githubusercontent.com/43357585/82678775-79036500-9c4a-11ea-8cbf-a9929603568a.png)

**Comment by giovannipizzi** [comment]
Thanks @CasperWA ! I think it would be good to involve also @waychal in these CSS discussions, as these problems might come from the CSS of Materials Cloud, so we might want to fix the CSS also there

**Comment by waychal** [comment]
@CasperWA We can have a look at it together and check where is the problem.

**Comment by CasperWA** [comment]
> @CasperWA We can have a look at it together and check where is the problem.

Sure! You can also check out the latest edition of the OPTIMADE client using the template [here](https://mybinder.org/v2/gh/aiidalab/aiidalab-optimade/mcloud?urlpath=%2Fvoila%2Frender%2FOPTIMADE_general.ipynb)
