### ISSUE TITLE
New release for jupyter dependency fix

### ISSUE THREAD

**Issue by unkcpz** [materialscloud-org/voila-materialscloud-template#79]
Hi @dou-du 

Would you mind to make a new release for the jupyter dependent fix? It fails the test on optimadeclient, although it not block anything but good to have it not show up again.

**Comment by dou-du** [comment]
> Hi @dou-du
> 
> Would you mind to make a new release for the jupyter dependent fix? It fails the test on optimadeclient, although it not block anything but good to have it not show up again.

Yes, I just released a new version 0.3.14.
